# Use the official Python image from Docker Hub
FROM python:latest

LABEL maintainer="hgholamhosseini@my.bcit.ca"

# Update the package manager and install Python and pip
RUN apt-get update -y && apt-get install -y python3 python3-pip

# Set the working directory inside the container
WORKDIR /app

# Copy your application files into the container
COPY . /app

# Install required Python packages
RUN pip install connexion swagger-ui-bundle requests pykafka sqlalchemy starlette

RUN pip3 install pytz Flask uvicorn
RUN pip install --no-cache-dir connexion[flask]
RUN pip install --upgrade connexion

# Set the entrypoint and default command for the container
ENTRYPOINT [ "python3" ]
CMD [ "app.py" ]
