FROM ubuntu:18.04

LABEL maintainer="hgholamhosseini@my.bcit.ca"
RUN apt-get update -y && apt-get install -y python3 python3-pip
# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip3 install -r requirements.txt
RUN python3 -m pip install pytz
RUN apt-get update && apt-get install -y sqlite3
COPY . /app
RUN python3 create_database.py
ENTRYPOINT [ "python3" ]
CMD ["app.py"]
