FROM python:3.7

LABEL maintainer="hgholamhosseini@my.bcit.ca"


RUN apt-get update -y && apt-get install -y python3 python3-pip build-essential libssl-dev
RUN apt-get install -y libffi-dev python3-dev

# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip3 install -r requirements.txt
COPY . /app

# ENTRYPOINT [ "python3" ]
CMD [ "python", "app.py" ]
